---

# THIS ROLE ISUSED BY BOTH OPSC AND DSE

# https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/security/secAuthAndRbacAbout.html
# https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/security/Auth/secEnableDseAuthenticator.html
  
# In the cassandra.yaml file the following should all be setup already, but make sure here:
- name: Configure DSE Unified Authentication authenticator, authorizer in cassandra.yaml.
  yedit:
    src: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    edits:
    - key: authenticator
      value: com.datastax.bdp.cassandra.auth.DseAuthenticator
    - key: authorizer
      value: com.datastax.bdp.cassandra.auth.DseAuthorizer

#Configure the DSE Authorizer in dse.yaml (/etc/dse/dse.yaml)
- name: Configure the DSE Authorizer in dse.yaml (/etc/dse/dse.yaml)
  yedit:
    src: "{{ dse_config_dir }}/dse.yaml"
    edits:
    - key: authorization_options.enabled
      value: true

# Configure DSE Authenticator in dse.yaml (/etc/dse/dse.yaml)
# Extended settings:
# allow_digest_with_kerberos: true
# plain_text_without_ssl: warn
# transitional_mode: disabled
# other_schemes:
# scheme_permissions: false
- name: Configure INTERNAL DSE Authenticator in dse.yaml (/etc/dse/dse.yaml)
  yedit:
    src: "{{ dse_config_dir }}/dse.yaml"
    edits:
    - key: authentication_options.enabled
      value: true
    - key: authentication_options.default_scheme
      value: internal



