
# Disable auto_bootstrap if this is a new Datacenter node
- name: Disable auto_bootstrap for new Datacenter if required
  yedit:
    src: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    edits:
    - key: auto_bootstrap
      value: false
      state: present

