---

# On 4x vCPU | 30.5 GB RAM service can fail to start in time, need to ignore_errors and then move to Cassandra port wait.
# Between [DSE start...] in log and [DSE up...] can be up to 1min 20 seconds
- name: Start cassandra or dse service
  service:
    name: "{{ srvc_name }}"
    state: restarted
  ignore_errors: true

# If this fails with "skipped" probably means the ansible machine cannot see port 9042 on the target node due to a security or firewall configuration.
- name: Wait for Cassandra process is up and running
  wait_for:
    host: "{{ ansible_host }}"
    port: 9042
    delay: 1
    timeout: 300
