---
- name: Install python pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "python-pip"
    - "python-dev"
    - "build-essential"
    
#- name: Install pyOpenSSL via pip
#  pip:
#    name: pyOpenSSL
#    state: present

 REMOVED ruamel.yaml, NO LONGER USED, DEFAULTS NOW TO PYYAML DUE TO RH ISSUE
- name: Install pyyaml via pip ( used by ansible/library/yedit)
  pip:
    name: pyyaml
    state: present

#Install the crypto extensions
- name: Install Java JCE - Java Cryptography Extensions
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "oracle-java8-unlimited-jce-policy"
    
    
