
# Activate DSE Unified Authentication
- hosts: add_node[0]
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_auth_activate_internal, when: not is_ldap_authentication | bool }
    - { role: security_auth_activate_ldap, when: is_ldap_authentication | bool }
