
# Clear the existing keystores ready for regeneration
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_clear_keystores }
    
# If 1) CA signed certs and 2) No DNS server entry for cert CN name
# modify /etc/hosts on new node and push in CN name (same value as signed certificate for node)
- hosts: add_datacenter
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: security_etc_hosts_file_configure, when: etc_hosts_file_configure | bool }

# Regenerate all core DSE cluster and OPSC DSECore cluster keystores (local)
# Generate new Datacenter keystores
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_create_truststores }
    - { role: security_create_keystores }


# Distribute new keystores for new Datacenter node only
- hosts: add_datacenter
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: security_distribute_keystores }

# Distribute the already existing common truststore to the new node
- hosts: add_datacenter
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: security_distribute_truststores }

    
# Activate DSE security features on new node
- hosts: add_datacenter
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_node_to_node }
    - { role: security_client_to_node }
    
# Fetch the pre-built (at install time) /var/lib/opscenter/ssl/agentKeyStore from the OPSC SERVER
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agent_fetch_keystore }
    
# Distribute the pre-built (at install time) /var/lib/opscenter/ssl/agentKeyStore to new node
- hosts: add_datacenter
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agent_distribute_keystore }

# Activate OPSC SERVER -> Agent SSL in Agent address.yaml
- hosts: add_datacenter
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agents_activate_ssl }
    
#Activate Audit logging on the new node if required
- hosts: add_datacenter
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_audit_logging_configure}
    
