
# Activate DSE Unified Authentication on OPSC DSECore nodes
# OPSC cluster never uses LDAP
- hosts: opsc_dsecore
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_auth_activate_internal }
    - { role: security_role_management_internal }
