

#create core DSE / OPSC storage node truststores and keystores (local)
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_create_truststores }
    - { role: security_create_keystores }
